version: '3.8'
services:
  db:
    image: postgres:15
    container_name: my_pg_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_database
    ports:
      - "5444:5432"    # <--- ИЗМЕНИТЕ ЭТО (было 5432:5432)()